# Generated by Django 4.2.2 on 2023-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toluport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('image', models.ImageField(upload_to='mystaticfiles/projectsimg')),
                ('title', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('live_url', models.URLField()),
                ('stacks', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
