# Generated by Django 4.2.2 on 2023-07-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toluport', '0003_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=255)),
                ('Certificate', models.ImageField(upload_to='media')),
            ],
        ),
    ]
