# Generated by Django 4.2.2 on 2023-07-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toluport', '0004_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='Course',
        ),
    ]
